sudo: required

language: python

python:
  - "2.7"

env: SCIDB_VER=16.9 ARROW_VER=0.7.1-1

services:
  - docker

before_install:
  - docker pull rvernica/scidb:${SCIDB_VER}
  - docker run
    --name scidb
    --detach
    --publish 8080:8080
    --volume `pwd`:/stream
    --env ARROW_VER=${ARROW_VER}
    rvernica/scidb:${SCIDB_VER}
  - while ! curl http://localhost:8080/version; do sleep 5; done
  - cd py_pkg

install:
  - docker exec --tty scidb /stream/py_pkg/tests/docker-install.sh
  - pip install --upgrade -r requirements.txt

script:
  - docker exec --tty scidb /stream/test.sh
  - pep8 .
  - pip install .

after_failure:
  - docker logs scidb
