language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

env: SCIDB_VER=19.11 SCIDB_IMG= ARROW_VER=0.9.0

services:
  - docker

before_install:
  - wget --no-verbose --output-document -
    https://github.com/Paradigm4/accelerated_io_tools/archive/v${SCIDB_VER}.2.tar.gz
    | tar --extract --gzip --directory=.

  - docker pull rvernica/scidb:${SCIDB_VER}${SCIDB_IMG}

  - docker run
    --detach
    --env ARROW_VER=${ARROW_VER}
    --name scidb
    --publish 8080:8080
    --volume /sys/fs/cgroup:/sys/fs/cgroup:ro
    --volume /tmp/$(mktemp --directory):/run
    --volume `pwd`:/stream
    rvernica/scidb:${SCIDB_VER}${SCIDB_IMG}

  - while ! curl http://localhost:8080/version; do sleep 5; done

install:
  - docker exec --tty scidb /stream/tests/docker-install.sh
  - pip install --upgrade -r py_pkg/requirements.txt
  - pip install py_pkg/

  - docker exec scidb apt-get install
    --assume-yes
    --no-install-recommends
    libpqxx-dev
  - docker exec scidb make
    --directory=/stream/accelerated_io_tools-${SCIDB_VER}.2
  - docker exec scidb cp
    /stream/accelerated_io_tools-${SCIDB_VER}.2/libaccelerated_io_tools.so
    /opt/scidb/${SCIDB_VER}/lib/scidb/plugins/
  - docker exec scidb iquery --afl --query "load_library('accelerated_io_tools')"

script:
  - docker exec scidb /stream/tests/test.sh
  - pycodestyle .
  - pytest
  - docker exec --env TRAVIS_PYTHON_VERSION=${TRAVIS_PYTHON_VERSION} scidb
    /stream/tests/py_pkg_examples.sh
  - docker exec scidb rm /stream/tests/py_pkg_examples.out
  - if [ "${TRAVIS_PYTHON_VERSION}" = "2.7" -o
         "${TRAVIS_PYTHON_VERSION}" = "3.4" ]; then
    ./tests/py_pkg_examples.sh "docker exec --tty scidb";
    fi

after_failure:
  - docker logs scidb
  - docker exec --tty scidb
    cat /opt/scidb/${SCIDB_VER}/DB-scidb/0/0/scidb-stdout.log
  - docker exec --tty scidb
    cat /opt/scidb/${SCIDB_VER}/DB-scidb/0/0/scidb-stderr.log
  - docker exec --tty scidb
    cat /opt/scidb/${SCIDB_VER}/DB-scidb/0/1/scidb-stdout.log
  - docker exec --tty scidb
    cat /opt/scidb/${SCIDB_VER}/DB-scidb/0/1/scidb-stderr.log
