sudo: required

language: python

python:
  - "2.7"

env: SCIDB_VER=16.9

services:
  - docker

before_install:
  - docker pull rvernica/scidb:${SCIDB_VER}
  - docker run
    --name scidb
    --detach
    --volume /dev/shm
    --volume /home/travis/build/Paradigm4/stream:/stream:ro
    --tmpfs /dev/shm:exec
    --publish 8080:8080
    rvernica/scidb:${SCIDB_VER}
  - while ! curl http://localhost:8080/version; do sleep 1; done
  - cp py_pkg

install:
  - pip install --upgrade -r requirements.txt

script:
  - pep8 .
  - pip install .

after_failure:
  - docker logs scidb
